---
- name: Update en upgrade APT packages
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade alle packages
      ansible.builtin.apt:
        upgrade: dist
