[servers]
linda ansible_host=10.24.43.2 proxmox_node=linda proxmox_template_vmid=106
roos ansible_host=10.24.43.3 proxmox_node=roos proxmox_template_vmid=103
jessica ansible_host=10.24.43.4 proxmox_node=jessica proxmox_template_vmid=105
