---
- name: Maak WordPress CT op Proxmox
  hosts: localhost
  gather_facts: false
  collections:
    - community.proxmox

  vars:
    proxmox_api_host: "10.24.43.2"
    proxmox_api_port: 8006
    proxmox_node: "linda"
    proxmox_api_user: "root@pam"
    proxmox_api_password: "pindakaas"

    ct_rootfs_storage: "local-lvm"
    ct_template: "local:vztmpl/debian-12-turnkey-wordpress_18.2-1_amd64.tar.gz"

    ct_memory: 512
    ct_cores: 1
    ct_disk: "local-lvm:10"
    ct_bridge: "vmbr0"

  pre_tasks:
    - name: Controleer dat klantnummer is opgegeven
      ansible.builtin.assert:
        that:
          - klantnummer is defined
          - klantnummer | length > 0
        fail_msg: "Geef een klantnummer op via -e klantnummer=123"

    - name: Stel hostname vast
      ansible.builtin.set_fact:
        ct_hostname: "wordpress-{{ klantnummer }}"

  tasks:
    - name: Maak de CT aan
      community.proxmox.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        validate_certs: false

        node: "{{ proxmox_node }}"
        state: present

        hostname: "{{ ct_hostname }}"
        ostemplate: "{{ ct_template }}"
        password: "{{ proxmox_api_password }}"

        cores: "{{ ct_cores }}"
        memory: "{{ ct_memory }}"
        disk: "{{ ct_disk }}"

        netif:
          net0: "name=eth0,bridge={{ ct_bridge }},ip=dhcp,firewall=1"

        onboot: true
        unprivileged: true

    - name: Start de CT
      community.proxmox.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        validate_certs: false

        node: "{{ proxmox_node }}"
        hostname: "{{ ct_hostname }}"
        state: started
          - "SSH public key geplaatst voor gebruiker {{ klantnummer }}"
          - "Private key staat op: {{ generated_private_key_path }}"
