---
- name: Maak 1 Proxmox container aan op basis van klantnummer
  hosts: proxmox
  become: yes

  vars:
    ct_hostname: "klant-{{ klantnummer }}"

  tasks:
    - name: Controleer of klantnummer is opgegeven
      ansible.builtin.fail:
        msg: "Geef een klantnummer op met -e 'klantnummer=12345'"
      when: klantnummer is not defined

    - name: Toon hostname
      ansible.builtin.debug:
        msg: "De container hostname wordt {{ ct_hostname }}"

    - name: Maak container aan
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        hostname: "{{ ct_hostname }}"
        vmid: "{{ klantnummer }}"
        password: "{{ ct_root_password }}"
        ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
        storage: "local-lvm"
        disk: "8"
        memory: "1024"
        cores: "1"
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip=dhcp"}'
        state: present
      delegate_to: localhost
        group: root
        mode: "0440"
